# Generated by Django 6.0.2 on 2026-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='Fecha y hora en la que el registro fue eliminado', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, db_comment='Tipo de role:\n                    ADM = Administrador,\n                    SUP = Supervisor,\n                    OPD = Operador de donantes,\n                    OPS = Operador de solicitudes,\n                    PIN = Personal de inmunología,\n                    CHO = Coordinador hospitalario\n                    USR = Usuario,', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
